repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
        name: check for newline
      - id: mixed-line-ending
        name: unify line endings
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        name: add trailing comma
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [markdown, yaml, json, toml]
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: ruff format
        require_serial: true
        language: system
        types: [python]
      - id: ruff-lint
        name: ruff lint
        entry: ruff check --select I --fix # sort imports and apply fixes
        require_serial: true
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy .
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
